data_path: data/clip-siamese/
repo_id: INDEEPA/clip-siamese
source_table: tables_OZ_geo_5500/processed/OZ_geo_5500.csv
pairwise_mapping_file: tables_OZ_geo_5500/processed/regex-pairwise-groups/regex-pairwise-groups_num-queries=20_patterns-dict-hash=a6223255f273e52a893ba7235e3c19b3/mapping.parquet
img_dataset_name: images_OZ_geo_5500
results_dir: train_results/

val_ratio: 0.1
test_ratio: 0.1
random_seed: 42

pos_neg_ratio: 1.0
hard_soft_ratio: 0.5
limit_train_pos_pairs_per_query: 2
limit_val_pos_pairs_per_query: 2
limit_test_pos_pairs_per_query: 2
limit_queries: 2

preload_model_name: cc12m_rubert_tiny_ep_1.pt
name_model_name: cointegrated/rubert-tiny
description_model_name: cointegrated/rubert-tiny
dropout: 0.5
contrastive_margin: 1.5
contrastive_threshold: auto

batch_size_per_device: 160
device: cuda
epochs: 2
lr: 9.0e-5
momentum: 0.9
weight_decay: 0.01
scheduler_patience: 2
best_ckpt_metric: ndcg_at_10
early_stop_patience: 3

mlflow_experiment: siamese/1fold
